### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by PeratX** [iTXTech/Daedalus#23]
- [ ] IPv6 Support (Resolve & Rules) (#7)
- [ ] WiFi exclusion list (#15)
- [ ] Backend socks5 proxy support (#20)

**Comment by PeratX** [comment]
@TeraDew 几经尝试，Android下VpnService无法route IPv6地址。只支持IPv6的DNS服务器，所以无法使用自定义规则。

**Comment by ljodan** [comment]
Can not be used, failed

**Comment by PeratX** [comment]
@ljodan What cannot be used? Please describe your problem in detail

**Comment by nathanatgit** [comment]
Could you please surpport import a local host file in rules？Now the rules have to sync online…

**Comment by cubakcabak** [comment]
can we have an option for rule list as a blacklist?

i try to use adaway hosts list to block ads, but it seems that daedalus still passed the hosts in that list to the dns server.

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PeratX** [comment]
Can you paste your rule file here? Thanks.

**Comment by cubakcabak** [comment]
i get the hostlist from adaway github wiki page

https://github.com/AdAway/AdAway/wiki/HostsSources

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PeratX** [comment]
If you can sure you have activated the rules, there must be something wrong with Daedalus.

**Comment by cubakcabak** [comment]
i have a question, what is the meaning of the setting option "local rule resolutions"?

does it enabled rules list to be resolved by daedalus when its on, and doesn't get passed to the upstream dns server?

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PeratX** [comment]
Yes

**Comment by cubakcabak** [comment]
yeah, i've turn that on too

the rule list are all green too

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cubakcabak** [comment]
my apologies, the rules is infact working.

it's seems that after i fiddled with the exampe "import builtin rule" and learning what's need to be put in what field, daedalus process it just right.

i try to see daedalus documentation in the wiki, but i guess it still worked on.

thank you for your response, and this great software.

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PeratX** [comment]
You are welcome.

**Comment by PeratX** [comment]
@nathanatgit Import external rule is Work in progress! You will see it these days in 1.10.0.

**Comment by farrellneil** [comment]
Hi, does this support DNSMASQ options such as --add-cpe-id

**Comment by PeratX** [comment]
Daedalus has added support for DNS over HTTPS and DNS over TLS.
They are new standard of DNS.
DNSCrypt is not a DNS standard.
